#!/bin/sh
project_root=$(pwd)
cd $project_root
sh ./lizard.sh

# Only run frontend lint if the directory exists
if [ -d "frontend" ]; then
  cd frontend
  npx lint-staged
  npm run lint
  cd ..
fi

cd $project_root

# Add backend linting and formatting
if [ -d "backend" ]; then
  cd backend
  npx lint-staged
  npm run lint
  cd ..
fi

exit 0
